name: Auto Test

on: [push, pull_request]

jobs:

  unit_test:
    runs-on: ubuntu-latest
    environment: vika
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        HOST: ${{ secrets.HOST }}
        TOKEN: ${{ secrets.TOKEN }}
        SPACE_ID: ${{ secrets.SPACE_ID }}
        DATASHEET_ID: ${{ secrets.DATASHEET_ID }}
        VIEW_ID: ${{ secrets.VIEW_ID }}
        NUMBER_FIELD_NAME: ${{ secrets.NUMBER_FIELD_NAME }}
      run: go test -v ./test/...
